const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const truth = require("./mission-map-truth.js");

assert.equal(truth.VERSION, "10.26");
assert.equal(truth.MAX_MISSION, 73);
assert.deepEqual(truth.validate(), [], "all Missions 1-73 must have valid authored map truth");
assert.equal(Object.keys(truth.MISSIONS).length, 73, "exactly Missions 1-73 are covered");
assert.equal(truth.get(74), null, "V10.26 must not silently reuse Mission 73 for later missions");

for(let level=1; level<=73; level++){
  const spec = truth.get(level);
  assert.equal(spec.level, level);
  assert(spec.landmarks.length >= 3, `Mission ${level} needs at least three meaningful map landmarks`);
  assert(spec.route.length >= 2, `Mission ${level} needs a visible objective route`);
  if(level <= 37) assert(spec.requiredActionIds.length >= 1, `Mission ${level} needs at least one real map interaction`);
  const scaled = truth.scale(level, 2400, 1800);
  assert(scaled.landmarks.every((item)=>item.x > 0 && item.x < 2400 && item.y > 0 && item.y < 1800));
}

assert.equal(truth.get(31).landmarks.filter((item)=>item.type === "home" && item.required).length, 4, "Mission 31 has four searchable homes");
assert.equal(truth.get(29).extraction, "helicopter", "Mission 29 uses real helicopter extraction");
assert(truth.get(24).landmarks.some((item)=>item.type === "bridge" && item.required), "Mission 24 includes its river crossing");
assert.equal(truth.get(13).captures, 2, "Mission 13 requires two live captures");
assert.equal(truth.get(33).civilians, 6, "Mission 33 has six survivors");
assert.equal(truth.get(34).captures, 3, "Mission 34 requires three live research captures");
assert.equal(truth.get(35).extraction, "vehicle", "Mission 35 uses a real convoy extraction");
assert.equal(truth.get(36).landmarks.filter((item)=>item.type === "research" && item.required).length, 3, "Mission 36 has three working sample sites");
assert.equal(truth.get(37).landmarks.filter((item)=>item.type === "fire").length, 4, "Mission 37 shows all four fire zones");
assert.equal(truth.get(38).tigers, 10, "Mission 38 keeps the exact ten-tiger swarm");
assert.equal(truth.get(39).tigers, 12, "Mission 39 keeps the exact twelve-tiger pack");
assert.equal(truth.get(40).landmarks.filter((item)=>item.type === "boss").length, 2, "Mission 40 shows both Alpha territories");
assert.equal(truth.get(41).civilians, 6, "Mission 41 keeps six escorted civilians");
assert.equal(truth.get(41).landmarks.filter((item)=>item.type === "bridge" && item.required).length, 2, "Mission 41 shows its working bridge route");
assert.equal(truth.get(42).tigers, 7, "Mission 42 keeps the exact seven-tiger riverbank attack");
assert.equal(truth.get(43).captures, 1, "Mission 43 requires Currentstripe to be captured alive");
assert.equal(truth.get(44).civilians, 1, "Mission 44 keeps the wounded villager escort");
assert.equal(truth.get(44).tigers, 4, "Mission 44 keeps its four river threats");
assert.equal(truth.get(45).tigers, 8, "Mission 45 keeps the exact eight-tiger crossing ambush");
assert.equal(truth.get(46).civilians, 4, "Mission 46 keeps the four-person supply convoy");
assert.equal(truth.get(46).tigers, 5, "Mission 46 keeps its five convoy attackers");
assert.equal(truth.get(47).civilians, 7, "Mission 47 keeps seven escorted civilians");
assert.equal(truth.get(47).tigers, 5, "Mission 47 keeps its five River Camp attackers");
assert.equal(truth.get(48).civilians, 4, "Mission 48 keeps the four-person rescue-boat crew");
assert.equal(truth.get(48).tigers, 7, "Mission 48 keeps its seven boat attackers");
assert.equal(truth.get(48).extraction, "boat", "Mission 48 uses real boat extraction");
assert.equal(truth.get(49).tigers, 11, "Mission 49 keeps the exact eleven-tiger delta pack");
assert.equal(truth.get(49).landmarks.filter((item)=>item.type === "river").length, 2, "Mission 49 shows both delta channels");
assert.equal(truth.get(50).tigers, 1, "Mission 50 keeps one Giant River Tiger");
assert.equal(truth.get(50).landmarks.filter((item)=>item.type === "boss").length, 1, "Mission 50 shows the Giant River Tiger territory");
assert.equal(truth.get(51).civilians, 6, "Mission 51 keeps six mountain villagers");
assert.equal(truth.get(51).tigers, 4, "Mission 51 keeps its four ridge tigers");
assert.equal(truth.get(51).landmarks.filter((item)=>item.required).length, 3, "Mission 51 keeps three working ridge checkpoints");
assert.equal(truth.get(52).tigers, 7, "Mission 52 keeps the exact seven-tiger cliff attack");
assert.equal(truth.get(53).captures, 1, "Mission 53 requires Silverpeak to be captured alive");
assert.equal(truth.get(53).tigers, 4, "Mission 53 keeps Silverpeak and its three guards");
assert.equal(truth.get(54).civilians, 4, "Mission 54 keeps all four trapped climbers");
assert.equal(truth.get(54).landmarks.filter((item)=>item.required).length, 4, "Mission 54 shows the climber search and three descent checkpoints");
assert.equal(truth.get(55).tigers, 9, "Mission 55 keeps the exact nine-tiger mountain-road pack");
assert.equal(truth.get(55).landmarks.filter((item)=>item.type === "road" && item.required).length, 2, "Mission 55 shows the mountain road and hairpin");
assert.equal(truth.get(56).civilians, 5, "Mission 56 keeps all five caravan members");
assert.equal(truth.get(56).tigers, 5, "Mission 56 keeps its five canyon attackers");
assert.equal(truth.get(57).tigers, 7, "Mission 57 keeps the exact seven-tiger whiteout patrol");
assert.equal(truth.get(57).landmarks.filter((item)=>item.type === "beacon" && item.required).length, 3, "Mission 57 shows all three working visibility beacons");
assert.equal(truth.get(58).civilians, 5, "Mission 58 keeps all five mountain-rescue crew members");
assert.equal(truth.get(58).tigers, 6, "Mission 58 keeps its six LZ attackers");
assert.equal(truth.get(58).extraction, "helicopter", "Mission 58 uses real helicopter extraction");
assert.equal(truth.get(58).landmarks.filter((item)=>item.required).length, 4, "Mission 58 shows the crew camp and three working LZ checkpoints");
assert.equal(truth.get(59).tigers, 12, "Mission 59 keeps the exact twelve-tiger mountain swarm");
assert.equal(truth.get(60).tigers, 1, "Mission 60 keeps one Mountain Alpha");
assert.equal(truth.get(60).landmarks.filter((item)=>item.type === "boss").length, 1, "Mission 60 shows the Mountain Alpha territory");
assert.equal(truth.get(61).civilians, 6, "Mission 61 keeps all six research scientists");
assert.equal(truth.get(61).tigers, 5, "Mission 61 keeps its five territorial tigers");
assert.equal(truth.get(61).landmarks.filter((item)=>item.required).length, 4, "Mission 61 shows the research camp and three working checkpoints");
assert.equal(truth.get(62).tigers, 8, "Mission 62 keeps the exact eight cave guards");
assert.equal(truth.get(62).landmarks.filter((item)=>item.type === "den" && item.required).length, 4, "Mission 62 shows all four working cave entrances");
assert.equal(truth.get(63).captures, 4, "Mission 63 requires four live research captures");
assert.equal(truth.get(63).tigers, 6, "Mission 63 keeps four capture targets and two guards");
assert.equal(truth.get(63).landmarks.filter((item)=>item.type === "cage").length, 5, "Mission 63 shows four capture zones and the conservation pen");
assert.equal(truth.get(64).civilians, 7, "Mission 64 keeps all seven tunnel villagers");
assert.equal(truth.get(64).tigers, 6, "Mission 64 keeps its six tunnel pursuers");
assert.equal(truth.get(64).landmarks.filter((item)=>item.type === "den" && item.required).length, 3, "Mission 64 shows all three working tunnel stages");
assert.equal(truth.get(65).tigers, 13, "Mission 65 keeps the exact thirteen-tiger territory pack");
assert.equal(truth.get(66).civilians, 4, "Mission 66 keeps all four base specialists");
assert.equal(truth.get(66).tigers, 10, "Mission 66 keeps its ten base attackers");
assert.equal(truth.get(66).landmarks.filter((item)=>item.required).length, 4, "Mission 66 shows the specialists and three working defense posts");
assert.equal(truth.get(67).tigers, 8, "Mission 67 keeps the exact eight night Stalkers");
assert.equal(truth.get(67).landmarks.filter((item)=>item.type === "beacon" && item.required).length, 3, "Mission 67 shows all three working night beacons");
assert.equal(truth.get(68).civilians, 1, "Mission 68 keeps its protected lead scientist");
assert.equal(truth.get(68).tigers, 9, "Mission 68 keeps its nine equipment-site attackers");
assert.equal(truth.get(68).landmarks.filter((item)=>item.required).length, 4, "Mission 68 shows the scientist and three working equipment sites");
assert.equal(truth.get(69).tigers, 14, "Mission 69 keeps the exact fourteen-tiger aggression zone");
assert.equal(truth.get(69).landmarks.filter((item)=>item.required).length, 4, "Mission 69 shows its aggression perimeter, core, and fallback line");
assert.equal(truth.get(70).tigers, 1, "Mission 70 keeps one Legendary Blood Tiger");
assert.equal(truth.get(70).landmarks.filter((item)=>item.type === "boss").length, 1, "Mission 70 shows the Legendary Blood Tiger lair");
assert.equal(truth.get(71).civilians, 8, "Mission 71 keeps all eight fleeing villagers");
assert.equal(truth.get(71).tigers, 8, "Mission 71 keeps its eight pursuers");
assert.equal(truth.get(71).landmarks.filter((item)=>item.required).length, 4, "Mission 71 shows the refuge and three working evacuation checkpoints");
assert.equal(truth.get(72).civilians, 5, "Mission 72 keeps all five surrounded civilians");
assert.equal(truth.get(72).tigers, 6, "Mission 72 keeps the focused six-tiger ambush");
assert.equal(truth.get(72).requiredActionIds.length, 0, "Mission 72 adds no hidden map task beyond its visible rescue and ambush objectives");
assert.equal(truth.get(73).captures, 2, "Mission 73 requires both Elite Hunters captured alive");
assert.equal(truth.get(73).tigers, 5, "Mission 73 keeps two capture targets and three guards");
assert.equal(truth.get(73).landmarks.filter((item)=>item.type === "cage").length, 3, "Mission 73 shows both capture zones and the conservation pen");

const game = fs.readFileSync(path.join(__dirname, "game.js"), "utf8");
const coop = fs.readFileSync(path.join(__dirname, "squad-coop.js"), "utf8");
const server = fs.readFileSync(path.join(__dirname, "api/_lib/squad-session.js"), "utf8");
const html = fs.readFileSync(path.join(__dirname, "index.html"), "utf8");
assert(game.includes("drawMissionMapTruthOverlay({ mobileFast:true })"), "mobile map renders mission truth");
assert(game.includes("drawMissionMapTruthOverlay({ mobileFast:false })"), "full map renders mission truth");
assert(game.includes("missionMapTruthReady(S)"), "solo completion is gated by required visible map objectives");
assert(game.includes("activateMissionMapTruthInteractable"), "mission landmarks have real player interaction");
assert(game.includes("cfg.number <= 73"), "Solo Story applies exact Mission Map Truth counts through Mission 73");
assert(server.includes('require("../../mission-map-truth")'), "Live Squad uses the same mission truth manifest");
assert(server.includes("mapTruthLandmarks:mission.mapTruthLandmarks || []"), "Live Squad sends authored landmarks to both phones");
assert(coop.includes("drawSharedMissionTruth(ctx,snap)"), "Live Squad renders the shared mission landmarks");
assert(game.includes("missionMapTruthHazardTick"), "Solo Mission 37 fire is a real gameplay hazard");
assert(html.includes("mission-map-truth.js?v=5212-kings-reach"), "mission truth loads before gameplay");

console.log("mission-map-truth tests passed");
