const STARS_OFFERS = Object.freeze({
  funds_50: Object.freeze({
    sku: "funds_50",
    kind: "cash",
    name: "Scout Purse",
    stars: 50,
    funds: 500,
    desc: "Convert 50 Stars into $500 in-game cash.",
    grant: Object.freeze({ funds: 500 }),
  }),
  funds_100: Object.freeze({
    sku: "funds_100",
    kind: "cash",
    name: "Supply Cache",
    stars: 100,
    funds: 1000,
    desc: "Convert 100 Stars into $1,000 in-game cash.",
    grant: Object.freeze({ funds: 1000 }),
  }),
  funds_250: Object.freeze({
    sku: "funds_250",
    kind: "cash",
    name: "Field Treasury",
    stars: 250,
    funds: 2500,
    desc: "Convert 250 Stars into $2,500 in-game cash.",
    grant: Object.freeze({ funds: 2500 }),
  }),
  funds_350: Object.freeze({
    sku: "funds_350",
    kind: "cash",
    name: "Taskforce Reserve",
    stars: 350,
    funds: 3500,
    desc: "Convert 350 Stars into $3,500 in-game cash.",
    grant: Object.freeze({ funds: 3500 }),
  }),
  funds_450: Object.freeze({
    sku: "funds_450",
    kind: "cash",
    name: "Top-up Gateway 450",
    stars: 450,
    funds: 4500,
    desc: "Top-up gateway checkout. If paid, grants $4,500 in-game cash.",
    grant: Object.freeze({ funds: 4500 }),
  }),
  funds_2500: Object.freeze({
    sku: "funds_2500",
    kind: "cash",
    name: "Strategic Reserve",
    stars: 2500,
    funds: 25000,
    desc: "Convert 2,500 Stars into $25,000 in-game cash.",
    grant: Object.freeze({ funds: 25000 }),
  }),
  funds_5000: Object.freeze({
    sku: "funds_5000",
    kind: "cash",
    name: "High Command Vault",
    stars: 5000,
    funds: 50000,
    desc: "Convert 5,000 Stars into $50,000 in-game cash.",
    grant: Object.freeze({ funds: 50000 }),
  }),
  funds_10000: Object.freeze({
    sku: "funds_10000",
    kind: "cash",
    name: "Sovereign Treasury",
    stars: 10000,
    funds: 100000,
    desc: "Convert 10,000 Stars into $100,000 in-game cash.",
    grant: Object.freeze({ funds: 100000 }),
  }),
  funds_25000: Object.freeze({
    sku: "funds_25000",
    kind: "cash",
    name: "National Treasury",
    stars: 25000,
    funds: 250000,
    desc: "Convert 25,000 Stars into $250,000 in-game cash.",
    grant: Object.freeze({ funds: 250000 }),
  }),
  funds_35000: Object.freeze({
    sku: "funds_35000",
    kind: "cash",
    name: "Titan Treasury",
    stars: 35000,
    funds: 350000,
    desc: "Convert 35,000 Stars into $350,000 in-game cash.",
    grant: Object.freeze({ funds: 350000 }),
  }),

  // Legacy offers kept for backward compatibility with older pending orders.
  funds_150: Object.freeze({
    sku: "funds_150",
    kind: "cash",
    name: "Rapid Reserve",
    stars: 150,
    funds: 1500,
    desc: "Convert 150 Stars into $1,500 in-game cash.",
    grant: Object.freeze({ funds: 1500 }),
  }),
  funds_500: Object.freeze({
    sku: "funds_500",
    kind: "cash",
    name: "Legacy Reserve 500",
    stars: 500,
    funds: 5000,
    desc: "Legacy conversion 500 Stars -> $5,000 in-game cash.",
    grant: Object.freeze({ funds: 5000 }),
  }),
  funds_1000: Object.freeze({
    sku: "funds_1000",
    kind: "cash",
    name: "Legacy Reserve 1000",
    stars: 1000,
    funds: 10000,
    desc: "Legacy conversion 1,000 Stars -> $10,000 in-game cash.",
    grant: Object.freeze({ funds: 10000 }),
  }),

  premium_supply_drop: Object.freeze({
    sku: "premium_supply_drop",
    kind: "bundle",
    name: "Supply Drop",
    stars: 150,
    acceptedStars: Object.freeze([150, 350, 50]),
    desc: "Budget refill pack for active runs with better early value.",
    grant: Object.freeze({
      medkits: Object.freeze({ M_MED: 4 }),
      repairs: Object.freeze({ T_REPAIR: 4 }),
      traps: 6,
      shields: 3,
      ammo: Object.freeze({ TRANQ_DARTS: 30, "9MM_STD": 30 }),
    }),
  }),
  premium_arsenal_convoy: Object.freeze({
    sku: "premium_arsenal_convoy",
    kind: "bundle",
    name: "Arsenal Convoy",
    stars: 500,
    acceptedStars: Object.freeze([500, 1000, 250]),
    desc: "Large ammo shipment, weapon maintenance, and capture prep.",
    grant: Object.freeze({
      ammo: Object.freeze({ "9MM_STD": 160, "12GA_STD": 80, "556_STD": 110, "762_STD": 80, "TRANQ_DARTS": 70, TRANQ_HEAVY: 20 }),
      repairs: Object.freeze({ T_REPAIR_PRO: 4 }),
      traps: 8,
      shields: 6,
    }),
  }),
  premium_rescue_priority: Object.freeze({
    sku: "premium_rescue_priority",
    kind: "bundle",
    name: "Rescue Priority",
    stars: 1000,
    acceptedStars: Object.freeze([1000, 2500, 500]),
    desc: "Heavy rescue support for civilian-heavy routes and survival streaks.",
    grant: Object.freeze({
      shields: 18,
      traps: 18,
      medkits: Object.freeze({ M_TRAUMA: 8 }),
      armorPlates: Object.freeze({ A_TIER3: 8 }),
      repairs: Object.freeze({ T_REPAIR_PRO: 6 }),
    }),
  }),
  premium_forge_vault: Object.freeze({
    sku: "premium_forge_vault",
    kind: "bundle",
    name: "Forge Vault",
    stars: 750,
    acceptedStars: Object.freeze([750, 1000, 500]),
    desc: "Cosmetic-focused Stars sink for weapon skins and trail effects.",
    grant: Object.freeze({
      forgeMaterials: Object.freeze({ alloy: 100, bio_resin: 60, ion_dust: 24 }),
    }),
  }),
  premium_boss_hunt_reserve: Object.freeze({
    sku: "premium_boss_hunt_reserve",
    kind: "bundle",
    name: "Boss Hunt Reserve",
    stars: 1500,
    acceptedStars: Object.freeze([1500, 2500, 1000]),
    desc: "High-end boss and Alpha prep with elite ammo, shields, repairs, and forge materials.",
    grant: Object.freeze({
      perkPoints: 12,
      shields: 30,
      traps: 24,
      repairs: Object.freeze({ T_REPAIR_PRO: 12 }),
      ammo: Object.freeze({ "556_AP": 160, "762_AP": 140, TRANQ_HEAVY: 180, RAIL_CELL: 80 }),
      forgeMaterials: Object.freeze({ alloy: 80, bio_resin: 40, ion_dust: 12 }),
    }),
  }),
  premium_hq_modernization: Object.freeze({
    sku: "premium_hq_modernization",
    kind: "bundle",
    name: "HQ Modernization",
    stars: 2500,
    acceptedStars: Object.freeze([2500, 5000, 1500]),
    desc: "Long-term account progress pack for HQ upgrades, squad perks, cosmetics, and mission supplies.",
    grant: Object.freeze({
      perkPoints: 22,
      shields: 50,
      traps: 50,
      medkits: Object.freeze({ M_FIELD_SURGERY: 12 }),
      repairs: Object.freeze({ T_REPAIR_APEX: 12 }),
      armorPlates: Object.freeze({ A_APEX: 14 }),
      ammo: Object.freeze({ TRANQ_HEAVY: 220, TRANQ_DARTS: 220, RAIL_CELL: 120 }),
      forgeMaterials: Object.freeze({ alloy: 180, bio_resin: 110, ion_dust: 42 }),
    }),
  }),
  premium_apex_evac_reserve: Object.freeze({
    sku: "premium_apex_evac_reserve",
    kind: "bundle",
    name: "Apex Evac Reserve",
    stars: 3500,
    acceptedStars: Object.freeze([3500, 5000, 2500]),
    desc: "Ultra-premium rescue, boss, and late-story reserve for players who want a serious strategic stockpile.",
    grant: Object.freeze({
      perkPoints: 35,
      shields: 85,
      traps: 85,
      medkits: Object.freeze({ M_FIELD_SURGERY: 22, M_TRAUMA: 20 }),
      repairs: Object.freeze({ T_REPAIR_APEX: 22 }),
      armorPlates: Object.freeze({ A_APEX: 28 }),
      ammo: Object.freeze({ "556_AP": 260, "762_AP": 220, TRANQ_HEAVY: 320, TRANQ_DARTS: 300, RAIL_CELL: 220 }),
      forgeMaterials: Object.freeze({ alloy: 280, bio_resin: 170, ion_dust: 70 }),
    }),
  }),
  premium_tiger_specialist_unlock: Object.freeze({
    sku: "premium_tiger_specialist_unlock",
    kind: "bundle",
    name: "Tiger Specialist Unlock",
    stars: 500,
    acceptedStars: Object.freeze([500, 1000, 250]),
    desc: "Instant unlock + recruitment of a Tiger Specialist.",
    grant: Object.freeze({
      specialists: Object.freeze({ attacker: 1 }),
      specialistUnlocks: Object.freeze({ attacker: true }),
    }),
  }),
  premium_rescue_specialist_unlock: Object.freeze({
    sku: "premium_rescue_specialist_unlock",
    kind: "bundle",
    name: "Rescue Specialist Unlock",
    stars: 500,
    acceptedStars: Object.freeze([500, 1000, 250]),
    desc: "Instant unlock + recruitment of a Rescue Specialist.",
    grant: Object.freeze({
      specialists: Object.freeze({ rescue: 1 }),
      specialistUnlocks: Object.freeze({ rescue: true }),
    }),
  }),
});

function getOffer(sku){
  if(!sku || typeof sku !== "string") return null;
  return STARS_OFFERS[sku] || null;
}

module.exports = {
  STARS_OFFERS,
  getOffer,
};
